(car '(pork beef chiken))
(cdr '(pork beef chiken))
(car (cdr '(pork beef chiken)))
(cadr '(pork beef chiken))
(list 'pork 'beef 'chiken)
'(cat (duck bat) ant)
(car '((peas carrots tomatoes) (pork beef chiken)))
(cdr '(peas carrots tomatoes)) 
(cdr (car '((peas carrots tomatoes) (pork beef chiken))))
(cdar '((peas carrots tomatoes) (pork beef chiken)))
(cddr '((peas carrots tomatoes) (pork beef chiken) duck))
(caddr '((peas carrots tomatoes) (pork beef chiken) duck))
(cddar '((peas carrots tomatoes) (pork beef chiken) duck))
(cadadr '((peas carrots tomatoes) (pork beef chiken) duck))
(cons 'chiken 'nil)
(cons 'chiken (cons 'nil 'pork))
(cons 'chiken ())
(cons 'chiken '(pork beff))
(cons 'chiken (cons 'pork (cons 'beaf ())))
(expt 2 3)
(expt 2 (+ 3 4))
'(expt 2 3)

(+ 1 1.0)
(expt 53 53)
(/ 4 6)
(/ 4.0 6)

(princ "Tutti Frutti")
(princ "He yelled \"Stop that thief!\" from the buzy street")
(eq 'fooo 'FoOo)
