(car '(pork beef chiken))
(cdr '(pork beef chiken))
(car (cdr '(pork beef chiken)))
(cadr '(pork beef chiken))
(list 'pork 'beef 'chiken)
'(cat (duck bat) ant)
(car '((peas carrots tomatoes) (pork beef chiken)))
(cdr '(peas carrots tomatoes)) 
(cdr (car '((peas carrots tomatoes) (pork beef chiken))))
(cdar '((peas carrots tomatoes) (pork beef chiken)))
(cddr '((peas carrots tomatoes) (pork beef chiken) duck))
(caddr '((peas carrots tomatoes) (pork beef chiken) duck))
(cddar '((peas carrots tomatoes) (pork beef chiken) duck))
(cadadr '((peas carrots tomatoes) (pork beef chiken) duck))
