(defparameter foo (make-string-output-stream))
(princ "This will go into foo." foo)
(princ "This will also go into foo." foo)
(format t "~a" (get-output-stream-string foo))
(let
  ((str (with-output-to-string (*standard-output*)
	  (princ "the sum of ")
	  (princ 5)
	  (princ " and ")
	  (princ 2)
	  (princ " is ")
	  (princ (+ 2 5))
	  )
	))
  (princ str))

