(defvar *arch-enemy* nil)
(defun pudding-eater (person)
  (cond ((eq person 'henry) (setf *arch-enemy* 'stupid-lisp-alien)
			    '(curse you lisp alien - you ate my pudding))
	((eq person 'jonny) (setf *arch-enemy* 'usekess-old-jonny)
			    '(i hope you choked on my pudding jonny))
	(t '(why you eat my pudding stranger?))))
(print (pudding-eater 'george-cloony))
(print *arch-enemy*)
(print (pudding-eater 'henry))
(print *arch-enemy*)
(print (pudding-eater 'jonny))
(print *arch-enemy*)
