;string
(format t "Add onion rings for only ~$ dollors more!" 1.5)
(fresh-line)
(princ (reverse (format nil "Add onion rings for only ~$ dollors more!" 1.5)))
(fresh-line)
(format t "I am printing ~s in the middle of this sentence." "foo")
(fresh-line)
(format t "I am printing ~a in the middle of this sentence." "foo")
(fresh-line)
(format t "I am printing ~10a within ten spaces of room." "foo") 
(fresh-line)
(format t "I am printing ~10@a within ten spaces of room." "foo") 
(fresh-line)
(format t "I am printing ~10,3a within ten (or more) spaces of room." "foo")
(fresh-line)
(format t "I am printing ~,,4a in the middle of this sentence." "foo")
(fresh-line)
(format t "The word ~,,4,'!a feels very important." "foo")
(fresh-line)
(format t "The word ~,,4,'!@a feels very important." "foo")
; numeric
(format t "The number 1000 in hexadecimal is ~x" 1000)
(fresh-line)
(format t "The number 1000 in binary is ~b" 1000)
(fresh-line)
(format t "The number 1000 in decimal is ~d" 1000)
(fresh-line)
(format t "Numbers with commas in them are ~:d times better." 1000000)
(fresh-line)
(format t "I am printing ~10d within tenspaces of room" 1000000)
(fresh-line)
(format t "I am printing ~10,'xd within tenspaces of room" 1000000)
(fresh-line)
(format t "PI can be estimated as ~4f" 3.141593)
(fresh-line)
(format t "PI can be estimated as ~,4f" 3.141593)
(fresh-line)
(format t "PI can be estimated as ~,4f" pi)
(fresh-line)
(format t "Percentages are ~,,2f percent better than fractions" 0.77)
(fresh-line)
(format t "I wish I had ~$ dollors in my bank account." 1000000.2)

