(progn (princ 22)
       (terpri)
       (princ 33))
(fresh-line)
(progn (princ 22)
       (fresh-line)
       (princ 33))
(fresh-line)
(progn (princ 22)
       (fresh-line)
       (fresh-line)
       (princ 33))
(fresh-line)
(progn (format t "this is on one line ~%")
       (format t "~%this is on another line"))
(fresh-line)
(progn (format t "this is on one line ~&")
       (format t "~&this is on another line"))
(fresh-line)
(format t "this will print ~5%on tow line spread far apart")
(fresh-line)
(format t "this will print ~5&on tow line spread far apart")

